#!/bin/bash
set -e -u -o pipefail
cd "$(dirname "${BASH_SOURCE[0]}")"

{
    sqlite3 <<'EOF'
.mode csv
.import ../data/erofa/DOR-numerique_v1.0.2.csv t
select "Grafie initiale","Grafie modifiée"
from t
where "Grafie initiale" != ''
EOF
} \
    | tr -d '"' \
    | sed 's/ *([^)]*)//g' \
    | LANG=C sort -u \
    | {
    # The coordonner entry is erroneous. Let our dict generation do the right thing
    #
    # Drop héro and héroïne to avoid removing the h for the meaning of héroique.
    # We then make the error of not removing the h for the drug, but oh well, that
    # seems like a less confusing error to make.
    grep -E -v 'coordonner|^héro\>|^héroïne\>|^héroïq'
    echo sinophone,sinofone # missing
} \
    | cat > dict.gen.csv

{
    sqlite3 <<'EOF'
.mode csv
create table t(before,after);
.import dict.gen.csv t
select replace(replace(before,"œ","oe"),"æ","ae") as rewritten, after
from t
where rewritten != before and rewritten != after
EOF
} \
    | tr -d '"' \
    | LANG=C sort \
    | cat >> dict.gen.csv

{
    sqlite3 <<'EOF'
.mode csv
create table t(before,after);
.import dict.gen.csv t
.import ../data/wiktionnaire/1990.csv t1990
select t1990.pre1990,after
from t1990
join t on t.before = t1990.post1990
where t1990.pre1990 != after -- chariot -> (1990) charriot -> (erofa) chariot
order by t1990.pre1990
EOF
} \
    | tr -d '"' \
    | cat >> dict.gen.csv

cp dict.gen.csv dict.external-sources.gen.csv

tail -n +2 ../data/homemade/dict-rect1990+erofa.adds.csv | cut -d , -f 1,2 >> dict.gen.csv

# Capitalized words in the dict are treated as exceptions, for
# cases when the capitalized version of the word is almost never the common
# noun, but is instead a proper noun that we don't want to rewrite
for w in Pierre Cannes Rennes Vienne Bordeaux; do
    echo $w,bug-if-displayed
done >> dict.gen.csv

{
    # sqlite doesn't support outer joins, so we do two left joins
    # to combine the wiktionary and lexique+recto/verso data.
    # In a couple of cases, the two dbs don't agree ("absous"
    # is one case), so we just drop these cases.
    # The resulting table includes regular plurals that we could
    # drop, but the table is small so whatever.
    sqlite3 <<'EOF'
.mode csv
.import ../data/lexique/1990.csv l
.import ../data/wiktionnaire/1990.csv w
select distinct l.ortho,coalesce(l.post90,w.post1990)
from l
left join w on l.ortho = w.pre1990
where (l.post90 is null
       or w.post1990 is null
       or l.post90 = w.post1990)
and l.type = 1
union all
select distinct w.pre1990,w.post1990
from w
left join l on l.ortho = w.pre1990
where l.ortho is null
and w.pre1990 <> w.post1990
and w.pre1990 = lower(w.pre1990)
order by 1
EOF
} \
    | tr -d '"' \
    | LANG=C sort \
    | cat >> dict1990.gen.csv

if [ "${INSIDE_DUNE-}" ]; then
    target=dict.js
else
    target=src/dict.js
fi
{
    echo -n 'const dict_erofa = "'; tr '\n' '/' < dict.gen.csv; echo '"';
    echo -n 'const dict_rect1990 = "'; tr '\n' '/' < dict1990.gen.csv; echo '"';
} > $target
