#!/bin/bash
set -e -u -o pipefail
cd "$(dirname "${BASH_SOURCE[0]}")"

if false; then
    :
else
    {
        sqlite3 <<'EOF'
.mode csv
.import ../data/erofa/DOR-numerique_v1.0.2.csv t
select "Grafie initiale","Grafie modifiée"
from t
where "Grafie initiale" != ''
EOF
    } \
        | tr -d '"' \
        | sed 's/ *([^)]*)//g' \
        | LANG=C sort -u \
        | {
        cat
        # missing
        echo ceux,ceus
        echo hispanophone,hispanofone
        echo sinophone,sinofone
        echo poux,pous
        echo choux,chous
        # corrections (last entry takes precedence when the dict is loaded)
        echo coordonner,coordoner
    } \
        | cat > dict.gen.csv

    # add a few conjugated forms, from EROFA as well
    ssconvert ../data/erofa/Verbes-conjugues-top-2k-Lexique.xlsx /tmp/tmp.csv
    {
        sqlite3 <<'EOF'
.mode csv
.import /tmp/tmp.csv t
select "1_ortho", "Grafie érofiène corecte" from t
union all
select "grafie alternative", "Grafie érofiène corecte" from t
where "grafie alternative" != '' and "grafie alternative" != "Grafie érofiène corecte"
EOF
    } \
        | tr -d '"' \
        | LANG=C sort \
        | cat >> dict.gen.csv

    {
        sqlite3 <<'EOF'
.mode csv
create table t(before,after);
.import dict.gen.csv t
select replace(replace(before,"œ","oe"),"æ","ae") as rewritten, after
from t
where rewritten != before and rewritten != after
EOF
    } \
        | tr -d '"' \
        | LANG=C sort \
        | cat >> dict.gen.csv

    {
        sqlite3 <<'EOF'
.mode csv
create table t(before,after);
.import dict.gen.csv t
.import ../data/wiktionnaire/1990.csv t1990
select t1990.pre1990,after
from t1990
join t on t.before = t1990.post1990
where t1990.pre1990 != after -- chariot -> (1990) charriot -> (erofa) chariot
order by t1990.pre1990
EOF
    } \
        | tr -d '"' \
        | cat >> dict.gen.csv

    cp dict.gen.csv dict.external-sources.gen.csv

    tail -n +2 ../data/homemade/dict.adds.csv | cut -d , -f 1,2 >> dict.gen.csv

    # Capitalized words in the dict are treated as exceptions, for
    # cases when the capitalized version of the word is almost never the common
    # noun, but is instead a proper noun that we don't want to rewrite
    for w in Pierre Cannes Rennes Vienne Bordeaux; do
        echo $w,bug-if-displayed
    done >> dict.gen.csv
fi

if [ "${INSIDE_DUNE-}" ]; then
    target=dict.js
else
    target=src/dict.js
fi
{ echo -n 'const dict_erofa = "'; tr '\n' '/' < dict.gen.csv; echo '"'; } > $target
