#!/bin/bash
set -e -u -o pipefail
missing_packages=()
for s in "dot graphviz" "qpdf qpdf"; do
    read prog package <<< "$s"
    if ! which $prog > /dev/null; then
        missing_packages=("${missing_packages[@]} $package")
    fi
done
if [ "${#missing_packages[@]}" -ne 0 ]; then
    echo >&2 "Missing system packages, please run: sudo apt install ${missing_packages[@]} (or equivalent)"
    exit 1
fi

# instructions from https://opam.ocaml.org/doc/Install.html
if ! which opam > /dev/null; then
    bash -c "sh <(curl -fsSL https://raw.githubusercontent.com/ocaml/opam/master/shell/install.sh)"
fi
