#!/bin/bash
set -e -u -o pipefail

function patdiff {
    ~/.opam/5.1.1/bin/patdiff "$@"
}

function manual-changes2 {
    unzip -l "$1" \
        | grep -E -o 'OPS/.*([.]html|[.]xhtml|[.]css)$' \
        | while read f; do
        { diff -u \
               <(unzip -p "$1" $f) \
               <(unzip -p "$2" $f) || true
          } | sed -e "1c--- $f" -e "2c+++ $f"
    done > manual-changes.diff
}

case "${1-}" in
    help)
        ebook-convert a.epub b.pdf --help | less;;
    orig)
        xdg-open 'https://fr.wikisource.org/wiki/Livre:Lewis_Caroll_-_Alice_au_pays_des_merveilles,_traduction_Henri_Bu%C3%A9.djvu'
        ;;
    pdf)
        # zoom a 73% pour ouvrir à taille réelle
        xdg-open Alice_au_pays_des_merveilles-manual-conv.pdf;;
    diff-epubs)
        shift
        unzip -l "$1" \
            | grep -E -o 'OPS/.*([.]html|[.]xhtml|[.]css)$' \
            | while read f; do
                 patdiff -keep-whitespace -context 0 -alt-old $f -alt-new $f \
                         <(unzip -p "$1" $f) \
                         <(unzip -p "$2" $f) || true
              done \
            |& grep -v "No newline at the end" \
            | less -R
        ;;
    *)
        # Améliorations possibles :
        # - le epub n'a pas la couverture
        #   cette page https://fr.wikisource.org/wiki/Page:Lewis_Caroll_-_Alice_au_pays_des_merveilles,_traduction_Henri_Bu%C3%A9.djvu/3
        #   serait mieux que la page qui sert actuellement de couverture
        #   dimensions: 11x18 x2 + dos de 9mm + 3-5mm de bord
        #     110+9+110+4*2 -> 237. 0, 4, 114, 123, 233, 237
        #     180+4*2 -> 188. 0, 4, 184, 188.
        # - la page des matiere ne montre pas les numéros de page
        server=http://localhost:8081
        server=https://orthographe-rationnelle.info
        if ! [ -f Alice_au_pays_des_merveilles.epub ]; then
            # the original, but since it's mutable, we pin the version
            url='https://ws-export.wmcloud.org/?format=epub&lang=fr&page=Alice_au_pays_des_merveilles'
            url="$server/static/Alice_au_pays_des_merveilles.epub"
            curl --no-progress-meter --fail-with-body -o Alice_au_pays_des_merveilles.epub "$url"
        fi
        if ! [ -f Alice_au_pays_des_merveilles-manual.epub ]; then
            curl --no-progress-meter --fail-with-body -o Alice_au_pays_des_merveilles-manual.epub "$server/static/Alice_au_pays_des_merveilles-manual.epub"
        fi
        manual-changes2 \
            Alice_au_pays_des_merveilles.epub \
            Alice_au_pays_des_merveilles-manual.epub
        root=$(jj workspace root 2> /dev/null || git rev-parse --show-toplevel)
        "$root"/_build/default/doc-conversion/bin/ortografe_cli.exe extract \
               Alice_au_pays_des_merveilles-manual.epub \
               -o /dev/stdout \
            | sed -e 's/très-/très /g' \
                  -e 's/Très-/Très /g' \
                  -e "s/grand’chose/grand-chose/g" \
                  -e "s/grand’/grand/g" \
                  -e "s/que hier/qu’hier/g" \
            | "$root"/_build/default/doc-conversion/bin/ortografe_cli.exe insert \
                     Alice_au_pays_des_merveilles-manual.epub \
                     -o Alice_au_pays_des_merveilles-manual-conv1.epub
        "$root"/_build/default/doc-conversion/bin/ortografe_cli.exe conv \
               Alice_au_pays_des_merveilles-manual-conv1.epub \
               -o Alice_au_pays_des_merveilles-manual-conv.epub \
               --erofa --1990 --oe --dict-file=<(
            echo clef,clé
            echo complétement,complètement # a l'air de précéder les rectifications de 1990, donc pas listé
            echo dî,di # le mot "dîner" coupé au milieu
            echo butta,buta # mot manquant, trop obscure
            echo pélerin,pèlerin # changement qui a lieu naturellement
            echo cuiller,cuillère # changement qui a lieu naturellement
        )
        ebook-convert \
            Alice_au_pays_des_merveilles-manual-conv.epub \
            Alice_au_pays_des_merveilles-manual-conv-tmp.pdf \
            --pdf-page-numbers \
            --pdf-use-document-margins \
            --pdf-default-font-size=16 \
            --pdf-page-number-map='n < 11 ? 0 : n - 11 + 1' \
            --remove-paragraph-spacing \
            --remove-paragraph-spacing-indent-size=-1 \
            --pdf-hyphenate $(true pour le chapitre 1, image du rideau) \
            --pdf-footer-template "$(cat <<EOF
<footer>
    <div style="margin: auto; font-size: smaller"></div>
    <script>
      if (_PAGENUM_ > 0) {
        document.currentScript.parentNode.querySelector("div").innerHTML = "" + _PAGENUM_
      }
    </script>
</footer>
EOF
)" \
            --extra-css <(
            if true; then
                # sizes meant for pocket books on lulu.com, along with cover2.svg
                content_width=8.6cm;
                content_height=13.7cm;
                page_width=11.4cm;
                page_height=18.1cm;
                margin="1.805cm 1.4cm 2.405cm 1.4cm"
            else
                # sizes meant for imprime-ton-livre.fr, along with cover.svg
                content_width=8.6cm;
                content_height=13.8cm;
                page_width=11cm;
                page_height=18cm;
                margin="1.8cm 1.2cm 2.4cm 1.2cm"
            fi
            cat <<EOF
__img {
  border: solid 1px blue;
}

/* any instance of <br style> indicates a bad split between text and image, so we remove
   them all (in the source) and join paragraphs that got split by images */

[data-title*="_02.png"] {
  /* lapin chap 1 */
  width: auto;
  height: calc(0.5 * $content_height);
  margin-bottom: 2em;
}
[data-title*="_03.png"] {
  /* somehow even with !important, we can override inline styles for the width and height,
     so we have to remove them from the epub */
  width: calc(0.60 * $content_width);
  height: auto;
  margin-bottom: -5px;
  margin-left: -5px;
}
[data-title*="_04.png"] {
  /* alice prend la bouteille */
  width: calc(0.55 * $content_width);
  height: auto;
  margin-top: -5px;
  margin-right: -5px;
  margin-bottom: -10px;
}
[data-title*="_05.png"] {
  width: auto;
  height: 13cm;
  margin: -5px -18px -5px -20px;
}

/* chap habitation du lapin */
[data-title*="_12.png"] {
  /* main qui prend le lapin */
  width: calc(0.60 * $content_width);
  height: auto;
  margin: -5px 0 -5px -5px;
}
[data-title*="_13.png"] {
  /* lézard cheminée */
  margin-right: -12px;
  margin-left: -5px;
}

/* chap chenille */
[data-title*="_05a-1116x1492.jpg"] {
  /* chenille qui fume */
  width: auto;
  height: calc(0.6 * $content_height);
  margin-bottom: 2em;
}

/* porc et poivre */
[data-title*="_22.png"] {
  /* cochon dans les bras */
  width: calc(0.60 * $content_width);
  height: auto;
  margin: -5px;
  margin-bottom: -15px;
}
#figure23 {
  /* chat dans l'arbre qui parle avec alice avec encart */
  shape-outside: polygon(0% 0%, 100% 0%, 100% 43%, 47% 43%, 47% 96%, 0% 96%);
}

/* le croquet */
[data-title*="_28.png"] {
  /* cartes qui se parlent */
  width: calc(0.60 * $content_width);
  height: auto;
  margin-bottom: -15px;
}
[data-title*="_30.png"] {
  /* cartes qui se parlent */
  width: calc(0.60 * $content_width);
  height: auto;
  margin-bottom: -5px;
}

/* histoire de la fausse-tortue */
[data-title*="_32.png"] {
  /* parle avec la duchesse */
  width: calc(0.60 * $content_width);
  height: auto;
  margin-bottom: -5px;
}

/* le quadrille de homard */
[data-title*="_36.png"] {
  /* homard */
  width: calc(0.65 * $content_width);
  height: auto;
  margin-bottom: -15px;
  margin-left: -5px;
}

/* qui a volé les tartes */
[data-title*="_38.png"] {
  /* chapelier */
  width: calc(0.65 * $content_width);
  height: auto;
  margin-bottom: -15px;
  margin-left: -10px;
}

/* la déposition d'alice */
#figure41 {
  /* roi qui regarde à droite */
  shape-outside: polygon(0% 0%, 55% 0%, 55% 70%, 100% 70%, 100% 97%, 0% 97%);
}

@page {
  size: $page_width $page_height;
  margin: $margin;
}

.mw-halign-center {
  /* remove display:table so we can put float: left, so we can have the text flow above
     the image, to avoid big gaps at page breaks that precede images. */
  display: block;
  float:left;
  width: 100%; /* ensure no text flows around the image */
  /* border: solid; */
}

.mw-halign-center a {
  /* so the image ("img" inside "a" inside "figure" with cass mw-halign-center) is centered
     within the a, instead of being flushed to the left. The simpler method would be to make
     the image display:block and margin:auto, but that prevent text from flowing around it,
     which is the whole point of using float here. */
  display: flex;
  justify-content: center;
  page-break-inside: avoid;
}

.poem {
  margin-left: 0.5em;
}

a {
  text-decoration: none;
  color: inherit;
}

/* __page {
  counter-increment: page;
} */
/* I think calibre might be too old to support target-counter, I should update
.tableItem a::after {
    content: "(page" target-counter(attr(href), page) ")"
}
*/
EOF
                         )
        qpdf Alice_au_pays_des_merveilles-manual-conv-tmp.pdf --pages . 2-z -- \
             Alice_au_pays_des_merveilles-manual-conv.pdf
        # rm -f Alice_au_pays_des_merveilles-manual-conv{,1}.epub
        rm -f Alice_au_pays_des_merveilles-manual-conv-tmp.pdf
esac
